version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 10000000000uggz
  - 200000000000stake
  mnemonic: later rookie jazz alter minute group share scan random try brain brain task afraid roast fuel ring autumn awake diamond length sadness please round  
- name: bob
  coins:
  - 10000000000uggz
  - 1000000000000stake
  mnemonic: float elder spice lamp blue cause office surge reopen brass stone garbage pistol noodle breeze fortune jewel flavor asthma dirt rubber lyrics vicious picnic  
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 50000uggz
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
build:
  ldflags:
    - "-X github.com/cosmos/cosmos-sdk/version.Name=ggezchain"
    - "-X github.com/cosmos/cosmos-sdk/version.AppName=ggezchaind"
    - "-X github.com/cosmos/cosmos-sdk/version.Version=dev-a1ba86b534ee9982ebe9cc74cbbb5bbd63f5f3af"
    - "-X github.com/cosmos/cosmos-sdk/version.Commit=a1ba86b534ee9982ebe9cc74cbbb5bbd63f5f3af"